name: testing ci

on:
  pull_request:
    branch: main

jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          node-version: 20

      - run: npm ci
      - run: npm test
      - run: npm run build
